# Domain Adaptation  (Part )

In [1]:
import pandas as pd
import numpy as np
import os
import sklearn
from tqdm import tqdm
from collections import Counter

In [2]:
# To generate the Rare Offensive Words

In [3]:
tqdm.pandas(desc='progress-bar')

In [4]:
Fast_Off="/Users/student/Fast_Offensive_Training.csv"

In [6]:
Fast_Off_pd = pd.read_csv(Fast_Off, encoding ='ISO-8859-1')
XFast=pd.DataFrame(data=Fast_Off_pd, columns=['Tweet'])

In [7]:
XFast['Tweet'] = XFast['Tweet'].replace('[^a-zA-Z ]', '', regex=True)

In [8]:
XF = XFast.apply(lambda x: x.astype(str).str.lower())

In [4]:
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.tokenize import TweetTokenizer

In [5]:
w_tokenizer = nltk.tokenize.WhitespaceTokenizer()
Lemmatizer = WordNetLemmatizer()
tokenizer= TweetTokenizer()

In [6]:
def lemmatize_text(Tweet):
    return [Lemmatizer.lemmatize(w) for w in w_tokenizer.tokenize(Tweet) if not w in set(stopwords.words('english'))]

In [12]:
XF['Tweet']=XF.Tweet.apply(lemmatize_text)

In [14]:
fast = XF['Tweet']

In [68]:
fast

0      [datemyfamily, wonder, he, single, coz, attitu...
1      [people, orania, voted, eff, think, impossible...
2      [im, sure, orania, vibrating, rn, brandy, koek...
3      [another, motherfucking, german, shepherd, gro...
4      [zulu, girl, pussy, good, rt, ntokomalo, charl...
5      [drag, queen, punk, rock, inquiry, open, thoug...
6      [peter, mulder, freedom, front, plus, said, le...
7      [need, fuckin, promotion, dawg, everybody, act...
8      [take, look, zulu, culture, perspective, child...
9      [nearly, died, said, brown, k, uhpeoplewas, sa...
10     [dont, know, south, africa, even, bothered, el...
11     [lol, absolute, fucking, joke, gormless, yarpi...
12     [look, like, biggest, gainer, south, africa, e...
13     [suck, dick, every, morning, thank, choosing, ...
14     [trevornaoh, played, video, thing, julius, mal...
15     [malema, cult, fvck, really, trevor, noah, por...
16     [trevor, played, clip, malema, talking, white,...
17     [still, dont, get, south

In [69]:
frequencies = Counter (word for sentence in fast for word in sentence)

In [78]:
n=5000
for word, frequency in frequencies.most_common()[:-n-1:-1]:
    print (word, frequency)


mayacamille 1
oddson 1
discovered 1
musty 1
aye 1
kyries 1
nbaquickreport 1
kyrie 1
hat 1
fishnet 1
stewart 1
beetle 1
gold 1
booster 1
martian 1
dcu 1
revitalize 1
paintball 1
payed 1
jealous 1
asl 1
lip 1
djunivercity 1
completely 1
eaten 1
recorded 1
aymanriane 1
dig 1
babymoma 1
fl 1
silk 1
los 1
misogynistic 1
debatinghiphop 1
lupe 1
liquor 1
nickatina 1
andre 1
phahahah 1
goth 1
weirdo 1
awwww 1
transparent 1
charlemagne 1
schoolboyq 1
till 1
heidiallen 1
meh 1
dong 1
bredda 1
tink 1
selbert 1
houston 1
sexist 1
douchebag 1
gaming 1
interacted 1
pervy 1
argued 1
spitefuldoll 1
ipliskinltjg 1
butterknife 1
scarecrow 1
slayer 1
mighty 1
strawman 1
attacking 1
scrapping 1
difference 1
here 1
samuelpeart 1
melted 1
heed 1
fuccn 1
east 1
actin 1
begged 1
annoying 1
cookie 1
dumbass 1
disability 1
extra 1
horseshit 1
empowerment 1
muted 1
dc 1
kaidownnn 1
morelos 1
alfredo 1
davidfindlay 1
mental 1
handling 1
default 1
womanhood 1
tawkin 1
burd 1
wide 1
subway 1
fav 1
rope 1
reappear 1

biden 1
fairy 1
elf 1
mystical 1
dummy 1
gaf 1
lebanese 1
armenian 1
fashion 1
beard 1
muslim 1
christian 1
itz 1
goodebumps 1
kidding 1
universe 1
gorgeous 1
precious 1
sweetest 1
piercings 1
septum 1
twat 1
turd 1
fart 1
tit 1
cocksucker 1
sol 1
aurora 1
marrying 1
cali 1
nda 1
nonbinary 1
refered 1
project 1
banned 1
rolledout 1
rafaknightrk 1
dev 1
shitshow 1
fellow 1
topic 1
throne 1
aaaaaaand 1
summer 1
niggazz 1
sunglass 1
mariejulienn 1
stevie 1
forem 1
btches 1
bar 1
finish 1
mustard 1
justmoonie 1
gamers 1
residentevilremake 1
residentevil 1
podcast 1
gamer 1
videogames 1
junktank 1
horror 1
scifi 1
indietv 1
supportindiefilm 1
indiefilm 1
webseries 1
comedy 1
filmmaker 1
filmmaking 1
liked 1
ammo 1
pile 1
froms 1
insufferable 1
posh 1
tonight 1
laundry 1
persona 1
mould 1
began 1
neoliberalism 1
embodiment 1
within 1
cell 1
sleeper 1
planted 1
task 1
prepare 1
culturereviewed 1
review 1
published 1
unsung 1
satirical 1
film 1
friday 1
rave 1
footage 1
cheap 1
mogadingoane 1


In [ ]:
# To generate Rare Hate Words

In [79]:
Fast_Hate="/Users/student/Fast_Hate_Training.csv"

In [80]:
Fast_Hate_pd = pd.read_csv(Fast_Hate, encoding ='ISO-8859-1')
XFast1=pd.DataFrame(data=Fast_Hate_pd, columns=['Tweet'])

In [81]:
XFast1['Tweet'] = XFast1['Tweet'].replace('[^a-zA-Z ]', '', regex=True)
XF1 = XFast1.apply(lambda x: x.astype(str).str.lower())

In [82]:
XF1['Tweet']=XF1.Tweet.apply(lemmatize_text)

In [83]:
fast1 = XF1['Tweet']

In [84]:
fast1

0     [racist, really, want, preferential, treatment...
1     [entire, election, outcome, right, wing, new, ...
2     [yup, give, want, dont, even, understand, gove...
3     [trevor, noah, sellout, genocide, he, taking, ...
4     [beyond, joke, understand, importance, thedail...
5     [im, rebellion, orania, concerned, beginning, ...
6     [people, voted, ff, please, move, orania, elec...
7          [clear, lunatic, orania, didnt, vote, right]
8     [quick, question, white, racist, orania, regis...
9     [dear, sa, medium, let, give, crazy, airtime, ...
10    [black, vote, mmusi, hope, enslave, orania, rt...
11    [chooseday, lesego, dithebe, already, imagine,...
12    [white, people, build, orania, land, black, ma...
13    [first, orania, eureka, enclave, racist, afrik...
14    [there, land, white, people, orania, efftshela...
15    [fight, thisinside, south, africa, whitesonly,...
16    [many, league, goal, gabuza, score, season, ma...
17    [absolutely, scary, well, eff, national, e

In [88]:
from collections import Counter

In [86]:
frequencies1 = Counter (word for sentence in fast1 for word in sentence)

In [87]:
n=5000
for word, frequency in frequencies1.most_common()[:-n-1:-1]:
    print (word, frequency)

hoe 1
damn 1
moved 1
fucked 1
footballer 1
failure 1
lamppost 1
touch 1
seen 1
ive 1
shittest 1
burke 1
transinclusive 1
intersectional 1
feminism 1
imo 1
athletics 1
includes 1
stuff 1
drjuliashaw 1
female 1
vagina 1
fucking 1
dick 1
ignorant 1
moffieelectionresults 1
sounding 1
jselet 1
monopoly 1
comment 1
annoys 1
ndoro 1
peter 1
sabcs 1
often 1
tell 1
bloodsucking 1
hesitate 1
immediately 1
heart 1
stake 1
ask 1
asian 1
young 1
childhood 1
love 1
dearmetenyearsago 1
gasantabarder 1
thevoyager 1
adhan 1
kerkklokke 1
moer 1
khoisan 1
practice 1
slave 1
immigrant 1
neither 1
tolerant 1
moffies 1
bible 1
extremely 1
public 1
positively 1
facebooks 1
violation 1
mattwalshblog 1
plain 1
disgusting 1
robinson 1
tommy 1
narrowminded 1
lady 1
swart 1
minded 1
narrow 1
neighbor 1
though 1
jesus 1
le 1
persios 1
flesh 1
rotting 1
smell 1
bekhusela 1
okhokho 1
mafrika 1
river 1
blood 1
isandlwane 1
battle 1
remember 1
tongue 1
picture 1
tweet 1
insisted 1
joe 1
son 1
bramhanekom 1
sisawufuna 

In [89]:
# To find the similarities between existing offensive tweets and our tweets, with many rare offensive words using Cosine Similarity

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer, TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

In [9]:
Dav_Off="/Users/student/Davidson_Offensive.csv"

In [10]:
Dav_Off_pd = pd.read_csv(Dav_Off, encoding ='ISO-8859-1')
Dav_df=pd.DataFrame(data=Dav_Off_pd, columns=['Tweet', 'Class'])

In [11]:
Dav_df['Tweet'] = Dav_df['Tweet'].replace('[^a-zA-Z ]', '', regex=True)
Dav_L = Dav_df.apply(lambda x: x.astype(str).str.lower())

In [12]:
Dav_L['Tweet']=Dav_L.Tweet.apply(lemmatize_text)

In [13]:
Dav_Off_Token = Dav_L['Tweet']

In [14]:
Dav_Off_Sentence = [' '.join(x) for x in Dav_Off_Token]

In [15]:
Dav_Off_Sentence

['rt mleew boy dat coldtyga dwn bad cuffin dat hoe st place',
 'rt urkindofbrand dawg rt sbabylife ever fuck bitch start cry confused shit',
 'rt cganderson vivabased look like tranny',
 'rt shenikaroberts shit hear might true might faker bitch told ya',
 'tmadisonx shit blow meclaim faithful somebody still fucking hoe',
 '',
 'amp',
 'rhythmixx hobby include fighting mariam',
 'keeks bitch curve everyone lol walked conversation like smh',
 'murda gang bitch gang land',
 'hoe smoke loser yea go ig',
 'bad bitch thing like',
 'bitch get',
 'bitch nigga miss',
 'bitch plz whatever',
 'bitch love',
 'bitch get cut everyday b',
 'black bottle amp',
 'broke bitch cant tell nothing',
 'cancel bitch like nino',
 'cant see hoe wont change',
 'fuck bitch dont even suck dick',
 'got ya bitch tip toeing hardwood floor',
 'pussy lip like heaven door',
 'met pussy ocean dr gave pussy pill',
 'spend money want bitch business',
 'txt old bitch new bitch pussy wetter',
 'id say im back old old bitch w

In [16]:
tfidf_Dav_Off = TfidfVectorizer().fit_transform(Dav_Off_Sentence)

In [17]:
tfidf_Dav_Off.shape

(15145, 18078)

In [ ]:
 # Generate TFIDF for Rare English Offensive Tweets

In [101]:
English_Rare_Off="/Users/student/English_Rare_Offensive_Tweets.csv"

In [102]:
Eng_Rare_Off_pd = pd.read_csv(English_Rare_Off, encoding ='ISO-8859-1')
Eng_Rare_Off_df=pd.DataFrame(data=Eng_Rare_Off_pd, columns=['Tweet', 'English_Count'])

In [105]:
Eng_Rare_Off_df['Tweet'] = Eng_Rare_Off_df['Tweet'].replace('[^a-zA-Z ]', '', regex=True)
Eng_Rare_Off_L = Eng_Rare_Off_df.apply(lambda x: x.astype(str).str.lower())

In [106]:
Eng_Rare_Off_L['Tweet']=Eng_Rare_Off_L.Tweet.apply(lemmatize_text)
Eng_Rare_Off_Token = Eng_Rare_Off_L['Tweet']
Eng_Rare_Off_Sentence = [' '.join(x) for x in Eng_Rare_Off_Token]
Eng_Rare_Off_Sentence

['satirical post comrade mmusimaimane unsung hero black consciousness got published culture review check quick laugh rt culturereviewed took acting prepare task ahead planted sleeper cell within da embodiment neoliberalism south africa slowly began learn way mould persona wanted read mmusimaimane',
 'yup definite mistake maybe bergie find way sign away mapleleafs actually would worth losing draft pick would forgiven habs rt morgo toronto medium auston matthew got point million dollar contract he worth every penny john tavares got point million dollar contract he worth penny mitch marner got point need new contract wont dick take million le',
 'man fk bro bitch thot thought soon right nigga make eye contact wit square as gonna sneaking eating dick noon every weekday rt hustlesimmons crazy men arguing ayesha curry wrong feel wonder called misogynistica woman married superstar basketball player surrounded groupie shes wrong wanting adored men like cmon',
 'saw statement ton hate crime kil

In [112]:
tfidf_Eng_Rare_Off.shape

(25, 683)

In [108]:
tfidf_Eng_Rare_Off = TfidfVectorizer().fit_transform(Eng_Rare_Off_Sentence)

In [ ]:
# Join the matrices for equal dimensionality

In [110]:
Join_Off = Eng_Rare_Off_Sentence + Dav_Off_Sentence 

In [111]:
tfidf_Join_Off = TfidfVectorizer().fit_transform(Join_Off)

In [117]:
tfidf_Join_Off.shape

(15170, 18292)

In [148]:
cosine_similarities_Eng_Off_1 = linear_kernel(tfidf_Join_Off[0:1], tfidf_Join_Off[25:15170]).flatten()

In [8]:
np.set_printoptions(edgeitems=20000)
np.core.arrayprint._line_width = 20000

In [149]:
cosine_similarities_Eng_Off_1

array([0.00419813, 0.0102463 , 0.00637504, 0.00446339, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.05724314, 0.        , 0.        ,
       0.        , 0.        , 0.01520266, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.08059629, 0.        ,
       0.06434169, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.04780947, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.02421458, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.00412858, 0.        , 0.04264257, 0.     

In [142]:
#cosine_similarities_Eng_Off0.sort()

In [135]:
#cosine_similarities_Eng_Off1

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [150]:
related_off_doc_1 = cosine_similarities_Eng_Off_1.argsort()[:-6:-1]

In [151]:
related_off_doc_1

array([ 2791,  6596,  5016, 12460,  7057], dtype=int64)

In [187]:
cosine_similarities_Eng_Off_2 = linear_kernel(tfidf_Join_Off[1:2], tfidf_Join_Off[25:15170]).flatten()
cosine_similarities_Eng_Off_3 = linear_kernel(tfidf_Join_Off[2:3], tfidf_Join_Off[25:15170]).flatten()
cosine_similarities_Eng_Off_4 = linear_kernel(tfidf_Join_Off[3:4], tfidf_Join_Off[25:15170]).flatten()
cosine_similarities_Eng_Off_5 = linear_kernel(tfidf_Join_Off[4:5], tfidf_Join_Off[25:15170]).flatten()
cosine_similarities_Eng_Off_6 = linear_kernel(tfidf_Join_Off[5:6], tfidf_Join_Off[25:15170]).flatten()
cosine_similarities_Eng_Off_7 = linear_kernel(tfidf_Join_Off[6:7], tfidf_Join_Off[25:15170]).flatten()
cosine_similarities_Eng_Off_8 = linear_kernel(tfidf_Join_Off[7:8], tfidf_Join_Off[25:15170]).flatten()
cosine_similarities_Eng_Off_9 = linear_kernel(tfidf_Join_Off[8:9], tfidf_Join_Off[25:15170]).flatten()
cosine_similarities_Eng_Off_10 = linear_kernel(tfidf_Join_Off[9:10], tfidf_Join_Off[25:15170]).flatten()

In [188]:
related_off_doc_2 = cosine_similarities_Eng_Off_2.argsort()[:-6:-1]
related_off_doc_3 = cosine_similarities_Eng_Off_3.argsort()[:-6:-1]
related_off_doc_4 = cosine_similarities_Eng_Off_4.argsort()[:-6:-1]
related_off_doc_5 = cosine_similarities_Eng_Off_5.argsort()[:-6:-1]
related_off_doc_6 = cosine_similarities_Eng_Off_6.argsort()[:-6:-1]
related_off_doc_7 = cosine_similarities_Eng_Off_7.argsort()[:-6:-1]
related_off_doc_8 = cosine_similarities_Eng_Off_8.argsort()[:-6:-1]
related_off_doc_9 = cosine_similarities_Eng_Off_9.argsort()[:-6:-1]
related_off_doc_10 = cosine_similarities_Eng_Off_10.argsort()[:-6:-1]

In [189]:
related_off_doc_2

array([ 4400,  4404, 12724,  8225,  4408], dtype=int64)

In [190]:
related_off_doc_3

array([15050, 13582, 14911,  6812, 12225], dtype=int64)

In [191]:
related_off_doc_4

array([14503,  7222,  6231,  6457,  9163], dtype=int64)

In [192]:
related_off_doc_5

array([ 7327,   786, 15001,  8744,  7421], dtype=int64)

In [193]:
related_off_doc_6

array([ 6165, 13093,  4502,  1340,  6642], dtype=int64)

In [194]:
related_off_doc_7

array([13720,  1600,  9067,  3548, 12213], dtype=int64)

In [195]:
related_off_doc_8

array([13003, 14503,   363,  2735, 11693], dtype=int64)

In [196]:
related_off_doc_9

array([ 8374, 14662,  7512, 12234, 12233], dtype=int64)

In [197]:
related_off_doc_10

array([ 6422, 14827, 14294,  5613,  5722], dtype=int64)

In [198]:
cosine_similarities_Eng_Off_11 = linear_kernel(tfidf_Join_Off[10:11], tfidf_Join_Off[25:15170]).flatten()
cosine_similarities_Eng_Off_12 = linear_kernel(tfidf_Join_Off[11:12], tfidf_Join_Off[25:15170]).flatten()
cosine_similarities_Eng_Off_13 = linear_kernel(tfidf_Join_Off[12:13], tfidf_Join_Off[25:15170]).flatten()
cosine_similarities_Eng_Off_14 = linear_kernel(tfidf_Join_Off[13:14], tfidf_Join_Off[25:15170]).flatten()
cosine_similarities_Eng_Off_15 = linear_kernel(tfidf_Join_Off[14:15], tfidf_Join_Off[25:15170]).flatten()
cosine_similarities_Eng_Off_16 = linear_kernel(tfidf_Join_Off[15:16], tfidf_Join_Off[25:15170]).flatten()
cosine_similarities_Eng_Off_17 = linear_kernel(tfidf_Join_Off[16:17], tfidf_Join_Off[25:15170]).flatten()
cosine_similarities_Eng_Off_18 = linear_kernel(tfidf_Join_Off[17:18], tfidf_Join_Off[25:15170]).flatten()
cosine_similarities_Eng_Off_19 = linear_kernel(tfidf_Join_Off[18:19], tfidf_Join_Off[25:15170]).flatten()
cosine_similarities_Eng_Off_20 = linear_kernel(tfidf_Join_Off[19:20], tfidf_Join_Off[25:15170]).flatten()

In [199]:
cosine_similarities_Eng_Off_21 = linear_kernel(tfidf_Join_Off[20:21], tfidf_Join_Off[25:15170]).flatten()
cosine_similarities_Eng_Off_22 = linear_kernel(tfidf_Join_Off[21:22], tfidf_Join_Off[25:15170]).flatten()
cosine_similarities_Eng_Off_23 = linear_kernel(tfidf_Join_Off[22:23], tfidf_Join_Off[25:15170]).flatten()
cosine_similarities_Eng_Off_24 = linear_kernel(tfidf_Join_Off[23:24], tfidf_Join_Off[25:15170]).flatten()
cosine_similarities_Eng_Off_25 = linear_kernel(tfidf_Join_Off[24:25], tfidf_Join_Off[25:15170]).flatten()

In [200]:
related_off_doc_11 = cosine_similarities_Eng_Off_11.argsort()[:-6:-1]
related_off_doc_12 = cosine_similarities_Eng_Off_12.argsort()[:-6:-1]
related_off_doc_13 = cosine_similarities_Eng_Off_13.argsort()[:-6:-1]
related_off_doc_14 = cosine_similarities_Eng_Off_14.argsort()[:-6:-1]
related_off_doc_15 = cosine_similarities_Eng_Off_15.argsort()[:-6:-1]
related_off_doc_16 = cosine_similarities_Eng_Off_16.argsort()[:-6:-1]
related_off_doc_17 = cosine_similarities_Eng_Off_17.argsort()[:-6:-1]
related_off_doc_18 = cosine_similarities_Eng_Off_18.argsort()[:-6:-1]
related_off_doc_19 = cosine_similarities_Eng_Off_19.argsort()[:-6:-1]
related_off_doc_20 = cosine_similarities_Eng_Off_20.argsort()[:-6:-1]
related_off_doc_21 = cosine_similarities_Eng_Off_21.argsort()[:-6:-1]
related_off_doc_22 = cosine_similarities_Eng_Off_22.argsort()[:-6:-1]
related_off_doc_23 = cosine_similarities_Eng_Off_23.argsort()[:-6:-1]
related_off_doc_24 = cosine_similarities_Eng_Off_24.argsort()[:-6:-1]
related_off_doc_25 = cosine_similarities_Eng_Off_25.argsort()[:-6:-1]

In [201]:
related_off_doc_11

array([11113,  5283,  4406, 14167, 11980], dtype=int64)

In [202]:
related_off_doc_12

array([12954, 11678,  4404, 11161,  9738], dtype=int64)

In [203]:
related_off_doc_13

array([ 4901,  7264, 14583,  7173, 12702], dtype=int64)

In [204]:
related_off_doc_14

array([ 7470,  5470, 12876,  8827,     9], dtype=int64)

In [205]:
related_off_doc_15

array([8873,  238, 5950, 8141, 3510], dtype=int64)

In [206]:
related_off_doc_16

array([13429,  3099, 14723, 14957,  9593], dtype=int64)

In [207]:
related_off_doc_17

array([7790, 9416, 6711, 7283, 4901], dtype=int64)

In [208]:
related_off_doc_18

array([14980,  5553,  4446,  6333,  4873], dtype=int64)

In [209]:
related_off_doc_19

array([ 6000,    30, 12794,  8497, 12701], dtype=int64)

In [210]:
related_off_doc_20

array([15135,  7944,  5315,  5962,  7390], dtype=int64)

In [211]:
related_off_doc_21

array([ 8283,  7067,  5552, 10291,  5926], dtype=int64)

In [212]:
related_off_doc_22

array([13773,  4793, 14944, 13703, 12679], dtype=int64)

In [213]:
related_off_doc_23

array([ 6596, 13018,  6670,  7057,  5467], dtype=int64)

In [214]:
related_off_doc_24

array([ 5078, 13389, 12855,  4381,  6094], dtype=int64)

In [215]:
related_off_doc_25

array([13588,  7901,  5199, 14853,  7900], dtype=int64)

In [ ]:
# To find the similarities between existing hate tweets and our tweets, with many rare hate words using Cosine Similarity

In [18]:
Dav_hate="/Users/student/Davidson_Hate.csv"
    

In [19]:
Dav_hate_pd = pd.read_csv(Dav_hate, encoding ='ISO-8859-1')
Dav_hate_df=pd.DataFrame(data=Dav_hate_pd, columns=['Tweet', 'Class'])

In [20]:
Dav_hate_df['Tweet'] = Dav_hate_df['Tweet'].replace('[^a-zA-Z ]', '', regex=True)
Dav_hate_L = Dav_hate_df.apply(lambda x: x.astype(str).str.lower())

In [21]:
Dav_hate_L['Tweet']=Dav_hate_L.Tweet.apply(lemmatize_text)
Dav_hate_Token = Dav_hate_L['Tweet']
Dav_hate_Sentence = [' '.join(x) for x in Dav_hate_Token]

In [22]:
tfidf_Dav_hate = TfidfVectorizer().fit_transform(Dav_hate_Sentence)
tfidf_Dav_hate.shape

(1217, 3387)

In [221]:
English_Rare_Hate="/Users/student/English_Rare_Hate_Tweets.csv"

In [222]:
Eng_Rare_Hate_pd = pd.read_csv(English_Rare_Hate, encoding ='ISO-8859-1')
Eng_Rare_Hate_df=pd.DataFrame(data=Eng_Rare_Hate_pd, columns=['Tweet', 'English_Count'])

In [224]:
Eng_Rare_Hate_df['Tweet'] = Eng_Rare_Hate_df['Tweet'].replace('[^a-zA-Z ]', '', regex=True)
Eng_Rare_Hate_L = Eng_Rare_Hate_df.apply(lambda x: x.astype(str).str.lower())

In [225]:
Eng_Rare_Hate_L['Tweet']=Eng_Rare_Hate_L.Tweet.apply(lemmatize_text)
Eng_Rare_Hate_Token = Eng_Rare_Hate_L['Tweet']
Eng_Rare_Hate_Sentence = [' '.join(x) for x in Eng_Rare_Hate_Token]

In [226]:
tfidf_Eng_Rare_Hate = TfidfVectorizer().fit_transform(Eng_Rare_Hate_Sentence)

In [229]:
tfidf_Eng_Rare_Hate.shape

(51, 829)

In [228]:
Join_Hate = Eng_Rare_Hate_Sentence + Dav_hate_Sentence 

In [230]:
tfidf_Join_Hate = TfidfVectorizer().fit_transform(Join_Hate)

In [231]:
tfidf_Join_Hate.shape

(1268, 3875)

In [233]:
cosine_similarities_Eng_Hate_1 = linear_kernel(tfidf_Join_Hate[0:1], tfidf_Join_Hate[51:1268]).flatten()

In [235]:
cosine_similarities_Eng_Hate_1 = linear_kernel(tfidf_Join_Hate[0:1], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_2 = linear_kernel(tfidf_Join_Hate[1:2], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_3 = linear_kernel(tfidf_Join_Hate[2:3], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_4 = linear_kernel(tfidf_Join_Hate[3:4], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_5 = linear_kernel(tfidf_Join_Hate[4:5], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_6 = linear_kernel(tfidf_Join_Hate[5:6], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_7 = linear_kernel(tfidf_Join_Hate[6:7], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_8 = linear_kernel(tfidf_Join_Hate[7:8], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_9 = linear_kernel(tfidf_Join_Hate[8:9], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_10 = linear_kernel(tfidf_Join_Hate[9:10], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_11 = linear_kernel(tfidf_Join_Hate[10:11], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_12 = linear_kernel(tfidf_Join_Hate[11:12], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_13 = linear_kernel(tfidf_Join_Hate[12:13], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_14 = linear_kernel(tfidf_Join_Hate[13:14], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_15 = linear_kernel(tfidf_Join_Hate[14:15], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_16 = linear_kernel(tfidf_Join_Hate[15:16], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_17 = linear_kernel(tfidf_Join_Hate[16:17], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_18 = linear_kernel(tfidf_Join_Hate[17:18], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_19 = linear_kernel(tfidf_Join_Hate[18:19], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_20 = linear_kernel(tfidf_Join_Hate[19:20], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_21 = linear_kernel(tfidf_Join_Hate[20:21], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_22 = linear_kernel(tfidf_Join_Hate[21:22], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_23 = linear_kernel(tfidf_Join_Hate[22:23], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_24 = linear_kernel(tfidf_Join_Hate[23:24], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_25 = linear_kernel(tfidf_Join_Hate[24:25], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_26 = linear_kernel(tfidf_Join_Hate[25:26], tfidf_Join_Hate[51:1268]).flatten()

In [236]:
cosine_similarities_Eng_Hate_27 = linear_kernel(tfidf_Join_Hate[26:27], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_28 = linear_kernel(tfidf_Join_Hate[27:28], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_29 = linear_kernel(tfidf_Join_Hate[28:29], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_30 = linear_kernel(tfidf_Join_Hate[29:30], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_31 = linear_kernel(tfidf_Join_Hate[30:31], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_32 = linear_kernel(tfidf_Join_Hate[31:32], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_33 = linear_kernel(tfidf_Join_Hate[32:33], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_34 = linear_kernel(tfidf_Join_Hate[33:34], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_35 = linear_kernel(tfidf_Join_Hate[34:35], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_36 = linear_kernel(tfidf_Join_Hate[35:36], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_37 = linear_kernel(tfidf_Join_Hate[36:37], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_38 = linear_kernel(tfidf_Join_Hate[37:38], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_39 = linear_kernel(tfidf_Join_Hate[38:39], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_40 = linear_kernel(tfidf_Join_Hate[39:40], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_41 = linear_kernel(tfidf_Join_Hate[40:41], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_42 = linear_kernel(tfidf_Join_Hate[41:42], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_43 = linear_kernel(tfidf_Join_Hate[42:43], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_44 = linear_kernel(tfidf_Join_Hate[43:44], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_45 = linear_kernel(tfidf_Join_Hate[44:45], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_46 = linear_kernel(tfidf_Join_Hate[45:46], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_47 = linear_kernel(tfidf_Join_Hate[46:47], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_48 = linear_kernel(tfidf_Join_Hate[47:48], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_49 = linear_kernel(tfidf_Join_Hate[48:49], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_50 = linear_kernel(tfidf_Join_Hate[49:50], tfidf_Join_Hate[51:1268]).flatten()
cosine_similarities_Eng_Hate_51 = linear_kernel(tfidf_Join_Hate[50:51], tfidf_Join_Hate[51:1268]).flatten()


In [238]:
related_hate_doc_1 = cosine_similarities_Eng_Hate_1.argsort()[:-6:-1]
related_hate_doc_2 = cosine_similarities_Eng_Hate_2.argsort()[:-6:-1]
related_hate_doc_3 = cosine_similarities_Eng_Hate_3.argsort()[:-6:-1]
related_hate_doc_4 = cosine_similarities_Eng_Hate_4.argsort()[:-6:-1]
related_hate_doc_5 = cosine_similarities_Eng_Hate_5.argsort()[:-6:-1]
related_hate_doc_6 = cosine_similarities_Eng_Hate_6.argsort()[:-6:-1]
related_hate_doc_7 = cosine_similarities_Eng_Hate_7.argsort()[:-6:-1]
related_hate_doc_8 = cosine_similarities_Eng_Hate_8.argsort()[:-6:-1]
related_hate_doc_9 = cosine_similarities_Eng_Hate_9.argsort()[:-6:-1]
related_hate_doc_10 = cosine_similarities_Eng_Hate_10.argsort()[:-6:-1]
related_hate_doc_11 = cosine_similarities_Eng_Hate_11.argsort()[:-6:-1]
related_hate_doc_12 = cosine_similarities_Eng_Hate_12.argsort()[:-6:-1]
related_hate_doc_13 = cosine_similarities_Eng_Hate_13.argsort()[:-6:-1]
related_hate_doc_14 = cosine_similarities_Eng_Hate_14.argsort()[:-6:-1]
related_hate_doc_15 = cosine_similarities_Eng_Hate_15.argsort()[:-6:-1]
related_hate_doc_16 = cosine_similarities_Eng_Hate_16.argsort()[:-6:-1]
related_hate_doc_17 = cosine_similarities_Eng_Hate_17.argsort()[:-6:-1]
related_hate_doc_18 = cosine_similarities_Eng_Hate_18.argsort()[:-6:-1]
related_hate_doc_19 = cosine_similarities_Eng_Hate_19.argsort()[:-6:-1]
related_hate_doc_20 = cosine_similarities_Eng_Hate_20.argsort()[:-6:-1]
related_hate_doc_21 = cosine_similarities_Eng_Hate_21.argsort()[:-6:-1]
related_hate_doc_22 = cosine_similarities_Eng_Hate_22.argsort()[:-6:-1]
related_hate_doc_23 = cosine_similarities_Eng_Hate_23.argsort()[:-6:-1]
related_hate_doc_24 = cosine_similarities_Eng_Hate_24.argsort()[:-6:-1]
related_hate_doc_25 = cosine_similarities_Eng_Hate_25.argsort()[:-6:-1]
related_hate_doc_26 = cosine_similarities_Eng_Hate_26.argsort()[:-6:-1]
related_hate_doc_27 = cosine_similarities_Eng_Hate_27.argsort()[:-6:-1]
related_hate_doc_28 = cosine_similarities_Eng_Hate_28.argsort()[:-6:-1]
related_hate_doc_29 = cosine_similarities_Eng_Hate_29.argsort()[:-6:-1]
related_hate_doc_30 = cosine_similarities_Eng_Hate_30.argsort()[:-6:-1]
related_hate_doc_31 = cosine_similarities_Eng_Hate_31.argsort()[:-6:-1]
related_hate_doc_32 = cosine_similarities_Eng_Hate_32.argsort()[:-6:-1]
related_hate_doc_33 = cosine_similarities_Eng_Hate_33.argsort()[:-6:-1]
related_hate_doc_34 = cosine_similarities_Eng_Hate_34.argsort()[:-6:-1]
related_hate_doc_35 = cosine_similarities_Eng_Hate_35.argsort()[:-6:-1]
related_hate_doc_36 = cosine_similarities_Eng_Hate_36.argsort()[:-6:-1]
related_hate_doc_37 = cosine_similarities_Eng_Hate_37.argsort()[:-6:-1]
related_hate_doc_38 = cosine_similarities_Eng_Hate_38.argsort()[:-6:-1]
related_hate_doc_39 = cosine_similarities_Eng_Hate_39.argsort()[:-6:-1]
related_hate_doc_40 = cosine_similarities_Eng_Hate_40.argsort()[:-6:-1]
related_hate_doc_41 = cosine_similarities_Eng_Hate_41.argsort()[:-6:-1]
related_hate_doc_42 = cosine_similarities_Eng_Hate_42.argsort()[:-6:-1]
related_hate_doc_43 = cosine_similarities_Eng_Hate_43.argsort()[:-6:-1]
related_hate_doc_44 = cosine_similarities_Eng_Hate_44.argsort()[:-6:-1]
related_hate_doc_45 = cosine_similarities_Eng_Hate_45.argsort()[:-6:-1]
related_hate_doc_46 = cosine_similarities_Eng_Hate_46.argsort()[:-6:-1]
related_hate_doc_47 = cosine_similarities_Eng_Hate_47.argsort()[:-6:-1]
related_hate_doc_48 = cosine_similarities_Eng_Hate_48.argsort()[:-6:-1]
related_hate_doc_49 = cosine_similarities_Eng_Hate_49.argsort()[:-6:-1]
related_hate_doc_50 = cosine_similarities_Eng_Hate_50.argsort()[:-6:-1]
related_hate_doc_51 = cosine_similarities_Eng_Hate_51.argsort()[:-6:-1]

In [239]:
related_hate_doc_1

array([1026, 1052,  124,  616,    3], dtype=int64)

In [240]:
related_hate_doc_2

array([ 539,  905,  717, 1079,  102], dtype=int64)

In [241]:
related_hate_doc_3

array([1072,   71,  813, 1048,  906], dtype=int64)

In [242]:
related_hate_doc_4

array([ 462,  873,  179, 1072,  774], dtype=int64)

In [243]:
related_hate_doc_5

array([1080,  531,  173,  343,  809], dtype=int64)

In [244]:
related_hate_doc_6

array([ 710,  634,  272,  331, 1152], dtype=int64)

In [245]:
related_hate_doc_7

array([ 743, 1027, 1211,  925,  409], dtype=int64)

In [246]:
related_hate_doc_8

array([1062,  124,  507,  276,  390], dtype=int64)

In [247]:
related_hate_doc_9

array([702, 281, 330, 743, 199], dtype=int64)

In [248]:
related_hate_doc_10

array([487, 597, 539, 848, 500], dtype=int64)

In [249]:
related_hate_doc_11

array([761, 573, 809, 995, 304], dtype=int64)

In [250]:
related_hate_doc_12

array([ 558,  600, 1215,   55,  294], dtype=int64)

In [251]:
related_hate_doc_13

array([ 408, 1200,  837,  622,  210], dtype=int64)

In [252]:
related_hate_doc_14

array([ 887, 1057,  487,  386,  976], dtype=int64)

In [253]:
related_hate_doc_15

array([279, 443, 816, 452, 720], dtype=int64)

In [254]:
related_hate_doc_16

array([1107, 1150,  601,  905, 1054], dtype=int64)

In [255]:
related_hate_doc_17

array([634, 780, 870, 343, 800], dtype=int64)

In [256]:
related_hate_doc_18

array([1158,  124, 1110,  910,  675], dtype=int64)

In [257]:
related_hate_doc_19

array([  55,  304,   17, 1203,   48], dtype=int64)

In [258]:
related_hate_doc_20

array([1055,  710,  973, 1142,  644], dtype=int64)

In [259]:
related_hate_doc_21

array([ 669, 1136,  590,  141,  296], dtype=int64)

In [260]:
related_hate_doc_22

array([1072, 1105, 1044,  891, 1171], dtype=int64)

In [261]:
related_hate_doc_23

array([1087, 1052,  710,  939,   55], dtype=int64)

In [262]:
related_hate_doc_24

array([ 626,  546,  170,  385, 1046], dtype=int64)

In [263]:
related_hate_doc_25

array([ 711, 1043,  787,  258, 1005], dtype=int64)

In [264]:
related_hate_doc_26

array([1072,  698,  565, 1030, 1080], dtype=int64)

In [265]:
related_hate_doc_27

array([1036,  174,  856,  732,  333], dtype=int64)

In [266]:
related_hate_doc_28

array([  62, 1081,  504,   17,  357], dtype=int64)

In [267]:
related_hate_doc_29

array([ 31, 702, 114, 902, 604], dtype=int64)

In [268]:
related_hate_doc_30

array([601, 241, 599, 242, 600], dtype=int64)

In [269]:
related_hate_doc_31

array([ 983, 1139,  423, 1096, 1030], dtype=int64)

In [270]:
related_hate_doc_32

array([601, 599, 600, 434, 905], dtype=int64)

In [271]:
related_hate_doc_33

array([   1,  296,  360, 1198,  797], dtype=int64)

In [272]:
related_hate_doc_34

array([ 754, 1021,  714,  776,  443], dtype=int64)

In [273]:
related_hate_doc_35

array([ 524, 1073,  689,   17, 1089], dtype=int64)

In [274]:
related_hate_doc_36

array([1121,  443,  161, 1194,  930], dtype=int64)

In [275]:
related_hate_doc_37

array([710,   3, 443, 539, 305], dtype=int64)

In [276]:
related_hate_doc_38

array([   3, 1057,  403,  851, 1123], dtype=int64)

In [277]:
related_hate_doc_39

array([ 679,  565, 1123,   22, 1033], dtype=int64)

In [278]:
related_hate_doc_40

array([1077,  247,  813,  587, 1025], dtype=int64)

In [279]:
related_hate_doc_41

array([1077,  247, 1072, 1038,  587], dtype=int64)

In [280]:
related_hate_doc_42

array([  60, 1123,  462,  258, 1141], dtype=int64)

In [281]:
related_hate_doc_43

array([ 621,  802,  656,  393, 1013], dtype=int64)

In [282]:
related_hate_doc_44

array([ 240,  141,  170, 1046,  837], dtype=int64)

In [283]:
related_hate_doc_45

array([257, 393, 416, 802,  92], dtype=int64)

In [284]:
related_hate_doc_46

array([ 985, 1087,  603,   11,  539], dtype=int64)

In [285]:
related_hate_doc_47

array([ 748, 1200,  602,  796, 1082], dtype=int64)

In [286]:
related_hate_doc_48

array([ 978,  546, 1079,  182,  717], dtype=int64)

In [287]:
related_hate_doc_49

array([978,  11, 675, 634, 979], dtype=int64)

In [288]:
related_hate_doc_50

array([ 573,  173,  762,  769, 1013], dtype=int64)

In [289]:
related_hate_doc_51

array([ 710,   55,  741, 1129, 1072], dtype=int64)

In [290]:
tfidf_Join_Hate[51:1268]

<1217x3875 sparse matrix of type '<class 'numpy.float64'>'
	with 8530 stored elements in Compressed Sparse Row format>

In [292]:
cosine_similarities_Eng_Hate_41.shape

(1217,)

In [ ]:
# To find the similarities between existing offensive tweets and our translated SA Offensive Tweets using Cosine Similarity

In [23]:
SA_Rare_Off="/Users/student/SA_Rare_Offensive_Translated.csv"
SA_Rare_Off_pd = pd.read_csv(SA_Rare_Off, encoding ='ISO-8859-1')
SA_Rare_Off_df=pd.DataFrame(data=SA_Rare_Off_pd, columns=['Tweet'])
SA_Rare_Off_df['Tweet'] = SA_Rare_Off_df['Tweet'].replace('[^a-zA-Z ]', '', regex=True)
SA_Rare_Off_L = SA_Rare_Off_df.apply(lambda x: x.astype(str).str.lower())
SA_Rare_Off_L['Tweet']=SA_Rare_Off_L.Tweet.apply(lemmatize_text)
SA_Rare_Off_Token = SA_Rare_Off_L['Tweet']
SA_Rare_Off_Sentence = [' '.join(x) for x in SA_Rare_Off_Token]

In [24]:
tfidf_SA_Rare_Off = TfidfVectorizer().fit_transform(SA_Rare_Off_Sentence)

In [25]:
tfidf_SA_Rare_Off.shape

(49, 872)

In [26]:
Join_Off_SA = SA_Rare_Off_Sentence + Dav_Off_Sentence 

In [27]:
tfidf_Join_Off_SA = TfidfVectorizer().fit_transform(Join_Off_SA)

In [28]:
tfidf_Join_Off_SA.shape

(15194, 18474)

In [31]:
cosine_similarities_SA_Off_1 = linear_kernel(tfidf_Join_Off_SA[0:1], tfidf_Join_Off_SA[49:15194]).flatten()

In [32]:
cosine_similarities_SA_Off_1 = linear_kernel(tfidf_Join_Off_SA[0:1], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_2 = linear_kernel(tfidf_Join_Off_SA[1:2], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_3 = linear_kernel(tfidf_Join_Off_SA[2:3], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_4 = linear_kernel(tfidf_Join_Off_SA[3:4], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_5 = linear_kernel(tfidf_Join_Off_SA[4:5], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_6 = linear_kernel(tfidf_Join_Off_SA[5:6], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_7 = linear_kernel(tfidf_Join_Off_SA[6:7], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_8 = linear_kernel(tfidf_Join_Off_SA[7:8], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_9 = linear_kernel(tfidf_Join_Off_SA[8:9], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_10 = linear_kernel(tfidf_Join_Off_SA[9:10], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_11= linear_kernel(tfidf_Join_Off_SA[10:11], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_12 = linear_kernel(tfidf_Join_Off_SA[11:12], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_13 = linear_kernel(tfidf_Join_Off_SA[12:13], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_14 = linear_kernel(tfidf_Join_Off_SA[13:14], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_15 = linear_kernel(tfidf_Join_Off_SA[14:15], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_16 = linear_kernel(tfidf_Join_Off_SA[15:16], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_17 = linear_kernel(tfidf_Join_Off_SA[16:17], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_18 = linear_kernel(tfidf_Join_Off_SA[17:18], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_19 = linear_kernel(tfidf_Join_Off_SA[18:19], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_20 = linear_kernel(tfidf_Join_Off_SA[19:20], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_21 = linear_kernel(tfidf_Join_Off_SA[20:21], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_22 = linear_kernel(tfidf_Join_Off_SA[21:22], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_23 = linear_kernel(tfidf_Join_Off_SA[22:23], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_24 = linear_kernel(tfidf_Join_Off_SA[23:24], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_25 = linear_kernel(tfidf_Join_Off_SA[24:25], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_26 = linear_kernel(tfidf_Join_Off_SA[25:26], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_27 = linear_kernel(tfidf_Join_Off_SA[26:27], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_28 = linear_kernel(tfidf_Join_Off_SA[27:28], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_29 = linear_kernel(tfidf_Join_Off_SA[28:29], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_30 = linear_kernel(tfidf_Join_Off_SA[29:30], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_31 = linear_kernel(tfidf_Join_Off_SA[30:31], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_32 = linear_kernel(tfidf_Join_Off_SA[31:32], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_33 = linear_kernel(tfidf_Join_Off_SA[32:33], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_34 = linear_kernel(tfidf_Join_Off_SA[33:34], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_35 = linear_kernel(tfidf_Join_Off_SA[34:35], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_36 = linear_kernel(tfidf_Join_Off_SA[35:36], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_37 = linear_kernel(tfidf_Join_Off_SA[36:37], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_38 = linear_kernel(tfidf_Join_Off_SA[37:38], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_39 = linear_kernel(tfidf_Join_Off_SA[38:39], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_40 = linear_kernel(tfidf_Join_Off_SA[39:40], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_41 = linear_kernel(tfidf_Join_Off_SA[40:41], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_42 = linear_kernel(tfidf_Join_Off_SA[41:42], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_43 = linear_kernel(tfidf_Join_Off_SA[42:43], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_44 = linear_kernel(tfidf_Join_Off_SA[43:44], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_45 = linear_kernel(tfidf_Join_Off_SA[44:45], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_46 = linear_kernel(tfidf_Join_Off_SA[45:46], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_47 = linear_kernel(tfidf_Join_Off_SA[46:47], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_48 = linear_kernel(tfidf_Join_Off_SA[47:48], tfidf_Join_Off_SA[49:15194]).flatten()
cosine_similarities_SA_Off_49 = linear_kernel(tfidf_Join_Off_SA[48:49], tfidf_Join_Off_SA[49:15194]).flatten()


In [34]:
related_SA_Off_doc_1 = cosine_similarities_SA_Off_1.argsort()[:-6:-1]
related_SA_Off_doc_2 = cosine_similarities_SA_Off_2.argsort()[:-6:-1]
related_SA_Off_doc_3 = cosine_similarities_SA_Off_3.argsort()[:-6:-1]
related_SA_Off_doc_4 = cosine_similarities_SA_Off_4.argsort()[:-6:-1]
related_SA_Off_doc_5 = cosine_similarities_SA_Off_5.argsort()[:-6:-1]
related_SA_Off_doc_6 = cosine_similarities_SA_Off_6.argsort()[:-6:-1]
related_SA_Off_doc_7 = cosine_similarities_SA_Off_7.argsort()[:-6:-1]
related_SA_Off_doc_8 = cosine_similarities_SA_Off_8.argsort()[:-6:-1]
related_SA_Off_doc_9 = cosine_similarities_SA_Off_9.argsort()[:-6:-1]
related_SA_Off_doc_10 = cosine_similarities_SA_Off_10.argsort()[:-6:-1]
related_SA_Off_doc_11 = cosine_similarities_SA_Off_11.argsort()[:-6:-1]
related_SA_Off_doc_12 = cosine_similarities_SA_Off_12.argsort()[:-6:-1]
related_SA_Off_doc_13 = cosine_similarities_SA_Off_13.argsort()[:-6:-1]
related_SA_Off_doc_14 = cosine_similarities_SA_Off_14.argsort()[:-6:-1]
related_SA_Off_doc_15 = cosine_similarities_SA_Off_15.argsort()[:-6:-1]
related_SA_Off_doc_16 = cosine_similarities_SA_Off_16.argsort()[:-6:-1]
related_SA_Off_doc_17 = cosine_similarities_SA_Off_17.argsort()[:-6:-1]
related_SA_Off_doc_18= cosine_similarities_SA_Off_18.argsort()[:-6:-1]
related_SA_Off_doc_19 = cosine_similarities_SA_Off_19.argsort()[:-6:-1]
related_SA_Off_doc_20= cosine_similarities_SA_Off_20.argsort()[:-6:-1]
related_SA_Off_doc_21= cosine_similarities_SA_Off_21.argsort()[:-6:-1]
related_SA_Off_doc_22= cosine_similarities_SA_Off_22.argsort()[:-6:-1]
related_SA_Off_doc_23= cosine_similarities_SA_Off_23.argsort()[:-6:-1]
related_SA_Off_doc_24= cosine_similarities_SA_Off_24.argsort()[:-6:-1]
related_SA_Off_doc_25= cosine_similarities_SA_Off_25.argsort()[:-6:-1]
related_SA_Off_doc_26= cosine_similarities_SA_Off_26.argsort()[:-6:-1]
related_SA_Off_doc_27= cosine_similarities_SA_Off_27.argsort()[:-6:-1]
related_SA_Off_doc_28 = cosine_similarities_SA_Off_28.argsort()[:-6:-1]
related_SA_Off_doc_29 = cosine_similarities_SA_Off_29.argsort()[:-6:-1]
related_SA_Off_doc_30 = cosine_similarities_SA_Off_30.argsort()[:-6:-1]
related_SA_Off_doc_31 = cosine_similarities_SA_Off_31.argsort()[:-6:-1]
related_SA_Off_doc_32= cosine_similarities_SA_Off_32.argsort()[:-6:-1]
related_SA_Off_doc_33 = cosine_similarities_SA_Off_33.argsort()[:-6:-1]
related_SA_Off_doc_34 = cosine_similarities_SA_Off_34.argsort()[:-6:-1]
related_SA_Off_doc_35 = cosine_similarities_SA_Off_35.argsort()[:-6:-1]
related_SA_Off_doc_36 = cosine_similarities_SA_Off_36.argsort()[:-6:-1]
related_SA_Off_doc_37 = cosine_similarities_SA_Off_37.argsort()[:-6:-1]
related_SA_Off_doc_38 = cosine_similarities_SA_Off_38.argsort()[:-6:-1]
related_SA_Off_doc_39 = cosine_similarities_SA_Off_39.argsort()[:-6:-1]
related_SA_Off_doc_40 = cosine_similarities_SA_Off_40.argsort()[:-6:-1]
related_SA_Off_doc_41 = cosine_similarities_SA_Off_41.argsort()[:-6:-1]
related_SA_Off_doc_42 = cosine_similarities_SA_Off_42.argsort()[:-6:-1]
related_SA_Off_doc_43 = cosine_similarities_SA_Off_43.argsort()[:-6:-1]
related_SA_Off_doc_44 = cosine_similarities_SA_Off_44.argsort()[:-6:-1]
related_SA_Off_doc_45 = cosine_similarities_SA_Off_45.argsort()[:-6:-1]
related_SA_Off_doc_46 = cosine_similarities_SA_Off_46.argsort()[:-6:-1]
related_SA_Off_doc_47 = cosine_similarities_SA_Off_47.argsort()[:-6:-1]
related_SA_Off_doc_48 = cosine_similarities_SA_Off_48.argsort()[:-6:-1]
related_SA_Off_doc_49 = cosine_similarities_SA_Off_49.argsort()[:-6:-1]

In [35]:
related_SA_Off_doc_1

array([13588,  7901,  5199, 14853,  7900], dtype=int64)

In [36]:
related_SA_Off_doc_2

array([ 5518,  7204, 13160,  3958, 12920], dtype=int64)

In [37]:
related_SA_Off_doc_3

array([  309, 14262, 10524,   145,  8533], dtype=int64)

In [38]:
related_SA_Off_doc_4

array([ 4901,  7264, 14583,  8155,  8154], dtype=int64)

In [39]:
related_SA_Off_doc_5

array([ 1580, 14289,  1577,   959, 14757], dtype=int64)

In [40]:
related_SA_Off_doc_6

array([13716, 14662, 13771, 13953,  5672], dtype=int64)

In [41]:
related_SA_Off_doc_7

array([4833, 5908, 4836, 3319, 4828], dtype=int64)

In [42]:
related_SA_Off_doc_8

array([   20, 14885,   384,  5068,   611], dtype=int64)

In [43]:
related_SA_Off_doc_9

array([14790, 14057,   363,  2581,  2853], dtype=int64)

In [44]:
related_SA_Off_doc_10

array([12252,  7352,  9331,  1992, 11405], dtype=int64)

In [45]:
related_SA_Off_doc_11

array([ 8865, 13007, 13820,  7088,  7672], dtype=int64)

In [46]:
related_SA_Off_doc_12

array([ 6165, 13093,  4502,  6642,  8704], dtype=int64)

In [47]:
related_SA_Off_doc_13

array([5034, 8616, 5384, 5573, 6319], dtype=int64)

In [48]:
related_SA_Off_doc_14

array([12954, 11678,  4404, 11161,  4400], dtype=int64)

In [49]:
related_SA_Off_doc_15

array([ 5462,  3292, 12662, 14296,  6658], dtype=int64)

In [50]:
related_SA_Off_doc_16

array([12474,  7154,  6263, 14612,  6262], dtype=int64)

In [51]:
related_SA_Off_doc_17

array([ 7088,  6519, 13820,  1649,  7566], dtype=int64)

In [52]:
related_SA_Off_doc_18

array([8801, 6447, 7387, 9113, 9883], dtype=int64)

In [53]:
related_SA_Off_doc_19

array([14175, 15127, 12265, 15109, 11326], dtype=int64)

In [54]:
related_SA_Off_doc_20

array([ 6231,  4451,  5040, 11715, 11682], dtype=int64)

In [55]:
related_SA_Off_doc_21

array([7122, 6025, 6971, 7390, 6970], dtype=int64)

In [56]:
related_SA_Off_doc_22

array([ 6596, 13018,  6670,  7057,  5467], dtype=int64)

In [57]:
related_SA_Off_doc_23

array([ 8764, 14484,  4773, 15001,  8744], dtype=int64)

In [58]:
related_SA_Off_doc_24

array([15050, 13582, 14911,  6812, 12225], dtype=int64)

In [59]:
related_SA_Off_doc_25

array([ 7468,  2952, 12953,  2286, 12613], dtype=int64)

In [60]:
related_SA_Off_doc_26

array([5425, 8845, 8306, 7902, 7754], dtype=int64)

In [61]:
related_SA_Off_doc_27

array([12441,  7961,  6503, 14503, 11006], dtype=int64)

In [62]:
related_SA_Off_doc_28

array([7204, 4917, 7603, 2087, 7605], dtype=int64)

In [63]:
related_SA_Off_doc_29

array([12184,   384, 14885,  7470,   611], dtype=int64)

In [64]:
related_SA_Off_doc_30

array([14612,  7230,  6263,  6262, 12474], dtype=int64)

In [65]:
related_SA_Off_doc_31

array([ 9120, 11713,  2750,  5044,  5056], dtype=int64)

In [66]:
related_SA_Off_doc_32

array([ 8608,  8052,  5951, 14938, 12543], dtype=int64)

In [67]:
related_SA_Off_doc_33

array([14781,  7164, 10466,  4502,  7605], dtype=int64)

In [68]:
related_SA_Off_doc_34

array([ 7775,  7762,  5584, 13666,  4785], dtype=int64)

In [69]:
related_SA_Off_doc_35

array([2916, 6038,  412, 4502, 8611], dtype=int64)

In [70]:
related_SA_Off_doc_36

array([13504, 14057,  6885, 14770,  6859], dtype=int64)

In [71]:
related_SA_Off_doc_37

array([14333,  8628,  8497, 12563,  8193], dtype=int64)

In [72]:
related_SA_Off_doc_38

array([ 4808,  8912,  7152, 13232,  4807], dtype=int64)

In [73]:
related_SA_Off_doc_39

array([ 2371,  1467,  7561, 14409,  1662], dtype=int64)

In [74]:
related_SA_Off_doc_40

array([11338,  7948,  5337,  5339,  5382], dtype=int64)

In [75]:
related_SA_Off_doc_41

array([ 5467, 14295,  4746,   605, 13909], dtype=int64)

In [76]:
related_SA_Off_doc_42

array([10826,  4652,  2626,  8481,  7758], dtype=int64)

In [77]:
related_SA_Off_doc_43

array([ 7044,  6774, 11366, 11697, 11384], dtype=int64)

In [78]:
related_SA_Off_doc_44

array([11641,  5553,  8744, 12299,  8100], dtype=int64)

In [79]:
related_SA_Off_doc_45

array([14585, 13849,  6799,  4805, 13852], dtype=int64)

In [80]:
related_SA_Off_doc_46

array([ 8153,  8155,  8154,    69, 10503], dtype=int64)

In [81]:
related_SA_Off_doc_47

array([14684, 15027,  6234, 14887, 14510], dtype=int64)

In [82]:
related_SA_Off_doc_48

array([  786, 15001,  8744,  7421,  7130], dtype=int64)

In [83]:
related_SA_Off_doc_49

array([ 5621, 12163, 13161,  7922,  5502], dtype=int64)

In [ ]:
#To find the similarities between existing hate tweets and SA translated Hate tweets using Cosine Similarities

In [84]:
SA_Rare_Hate="/Users/student/SA_Rare_Hate_Translated.csv"
SA_Rare_Hate_pd = pd.read_csv(SA_Rare_Hate, encoding ='ISO-8859-1')
SA_Rare_Hate_df=pd.DataFrame(data=SA_Rare_Hate_pd, columns=['Tweet'])
SA_Rare_Hate_df['Tweet'] = SA_Rare_Hate_df['Tweet'].replace('[^a-zA-Z ]', '', regex=True)
SA_Rare_Hate_L = SA_Rare_Hate_df.apply(lambda x: x.astype(str).str.lower())
SA_Rare_Hate_L['Tweet']=SA_Rare_Hate_L.Tweet.apply(lemmatize_text)
SA_Rare_Hate_Token = SA_Rare_Hate_L['Tweet']
SA_Rare_Hate_Sentence = [' '.join(x) for x in SA_Rare_Hate_Token]

In [85]:
tfidf_SA_Rare_Hate = TfidfVectorizer().fit_transform(SA_Rare_Hate_Sentence)

In [86]:
tfidf_SA_Rare_Hate.shape

(43, 683)

In [87]:
Join_Hate_SA = SA_Rare_Hate_Sentence + Dav_hate_Sentence 

In [88]:
tfidf_Join_Hate_SA = TfidfVectorizer().fit_transform(Join_Hate_SA)

In [89]:
tfidf_Join_Hate_SA.shape

(1260, 3787)

In [92]:
cosine_similarities_SA_HAte_1 = linear_kernel(tfidf_Join_Hate_SA[0:1], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_2 = linear_kernel(tfidf_Join_Hate_SA[1:2], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_3 = linear_kernel(tfidf_Join_Hate_SA[2:3], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_4 = linear_kernel(tfidf_Join_Hate_SA[3:4], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_5 = linear_kernel(tfidf_Join_Hate_SA[4:5], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_6 = linear_kernel(tfidf_Join_Hate_SA[5:6], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_7 = linear_kernel(tfidf_Join_Hate_SA[6:7], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_8 = linear_kernel(tfidf_Join_Hate_SA[7:8], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_9 = linear_kernel(tfidf_Join_Hate_SA[8:9], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_10 = linear_kernel(tfidf_Join_Hate_SA[9:10], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_11 = linear_kernel(tfidf_Join_Hate_SA[10:11], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_12 = linear_kernel(tfidf_Join_Hate_SA[11:12], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_13 = linear_kernel(tfidf_Join_Hate_SA[12:13], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_14 = linear_kernel(tfidf_Join_Hate_SA[13:14], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_15 = linear_kernel(tfidf_Join_Hate_SA[14:15], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_16 = linear_kernel(tfidf_Join_Hate_SA[15:16], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_17 = linear_kernel(tfidf_Join_Hate_SA[16:17], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_18 = linear_kernel(tfidf_Join_Hate_SA[17:18], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_19 = linear_kernel(tfidf_Join_Hate_SA[18:19], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_20 = linear_kernel(tfidf_Join_Hate_SA[19:20], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_21 = linear_kernel(tfidf_Join_Hate_SA[20:21], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_22 = linear_kernel(tfidf_Join_Hate_SA[21:22], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_23 = linear_kernel(tfidf_Join_Hate_SA[22:23], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_24 = linear_kernel(tfidf_Join_Hate_SA[23:24], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_25 = linear_kernel(tfidf_Join_Hate_SA[24:25], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_26 = linear_kernel(tfidf_Join_Hate_SA[25:26], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_27 = linear_kernel(tfidf_Join_Hate_SA[26:27], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_28 = linear_kernel(tfidf_Join_Hate_SA[27:28], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_29 = linear_kernel(tfidf_Join_Hate_SA[28:29], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_30 = linear_kernel(tfidf_Join_Hate_SA[29:30], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_31 = linear_kernel(tfidf_Join_Hate_SA[30:31], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_32 = linear_kernel(tfidf_Join_Hate_SA[31:32], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_33 = linear_kernel(tfidf_Join_Hate_SA[32:33], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_34 = linear_kernel(tfidf_Join_Hate_SA[33:34], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_35 = linear_kernel(tfidf_Join_Hate_SA[34:35], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_36 = linear_kernel(tfidf_Join_Hate_SA[35:36], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_37 = linear_kernel(tfidf_Join_Hate_SA[36:37], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_38 = linear_kernel(tfidf_Join_Hate_SA[37:38], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_39 = linear_kernel(tfidf_Join_Hate_SA[38:39], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_40 = linear_kernel(tfidf_Join_Hate_SA[39:40], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_41 = linear_kernel(tfidf_Join_Hate_SA[40:41], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_42 = linear_kernel(tfidf_Join_Hate_SA[41:42], tfidf_Join_Hate_SA[43:1260]).flatten()
cosine_similarities_SA_HAte_43 = linear_kernel(tfidf_Join_Hate_SA[42:43], tfidf_Join_Hate_SA[43:1260]).flatten()

In [95]:
related_SA_Hate_doc_1 = cosine_similarities_SA_HAte_1.argsort()[:-6:-1]
related_SA_Hate_doc_2 = cosine_similarities_SA_HAte_2.argsort()[:-6:-1]
related_SA_Hate_doc_3 = cosine_similarities_SA_HAte_3.argsort()[:-6:-1]
related_SA_Hate_doc_4 = cosine_similarities_SA_HAte_4.argsort()[:-6:-1]
related_SA_Hate_doc_5 = cosine_similarities_SA_HAte_5.argsort()[:-6:-1]
related_SA_Hate_doc_6 = cosine_similarities_SA_HAte_6.argsort()[:-6:-1]
related_SA_Hate_doc_7 = cosine_similarities_SA_HAte_7.argsort()[:-6:-1]
related_SA_Hate_doc_8 = cosine_similarities_SA_HAte_8.argsort()[:-6:-1]
related_SA_Hate_doc_9 = cosine_similarities_SA_HAte_9.argsort()[:-6:-1]
related_SA_Hate_doc_10 = cosine_similarities_SA_HAte_10.argsort()[:-6:-1]
related_SA_Hate_doc_11 = cosine_similarities_SA_HAte_11.argsort()[:-6:-1]
related_SA_Hate_doc_12 = cosine_similarities_SA_HAte_12.argsort()[:-6:-1]
related_SA_Hate_doc_13 = cosine_similarities_SA_HAte_13.argsort()[:-6:-1]
related_SA_Hate_doc_14 = cosine_similarities_SA_HAte_14.argsort()[:-6:-1]
related_SA_Hate_doc_15 = cosine_similarities_SA_HAte_15.argsort()[:-6:-1]
related_SA_Hate_doc_16 = cosine_similarities_SA_HAte_16.argsort()[:-6:-1]
related_SA_Hate_doc_17 = cosine_similarities_SA_HAte_17.argsort()[:-6:-1]
related_SA_Hate_doc_18 = cosine_similarities_SA_HAte_18.argsort()[:-6:-1]
related_SA_Hate_doc_19 = cosine_similarities_SA_HAte_19.argsort()[:-6:-1]
related_SA_Hate_doc_20= cosine_similarities_SA_HAte_20.argsort()[:-6:-1]
related_SA_Hate_doc_21 = cosine_similarities_SA_HAte_21.argsort()[:-6:-1]
related_SA_Hate_doc_22= cosine_similarities_SA_HAte_22.argsort()[:-6:-1]
related_SA_Hate_doc_23= cosine_similarities_SA_HAte_23.argsort()[:-6:-1]
related_SA_Hate_doc_24 = cosine_similarities_SA_HAte_24.argsort()[:-6:-1]
related_SA_Hate_doc_25 = cosine_similarities_SA_HAte_25.argsort()[:-6:-1]
related_SA_Hate_doc_26 = cosine_similarities_SA_HAte_26.argsort()[:-6:-1]
related_SA_Hate_doc_27= cosine_similarities_SA_HAte_27.argsort()[:-6:-1]
related_SA_Hate_doc_28 = cosine_similarities_SA_HAte_28.argsort()[:-6:-1]
related_SA_Hate_doc_29 = cosine_similarities_SA_HAte_29.argsort()[:-6:-1]
related_SA_Hate_doc_30 = cosine_similarities_SA_HAte_30.argsort()[:-6:-1]
related_SA_Hate_doc_31= cosine_similarities_SA_HAte_31.argsort()[:-6:-1]
related_SA_Hate_doc_32 = cosine_similarities_SA_HAte_32.argsort()[:-6:-1]
related_SA_Hate_doc_33 = cosine_similarities_SA_HAte_33.argsort()[:-6:-1]
related_SA_Hate_doc_34 = cosine_similarities_SA_HAte_34.argsort()[:-6:-1]
related_SA_Hate_doc_35= cosine_similarities_SA_HAte_35.argsort()[:-6:-1]
related_SA_Hate_doc_36 = cosine_similarities_SA_HAte_36.argsort()[:-6:-1]
related_SA_Hate_doc_37 = cosine_similarities_SA_HAte_37.argsort()[:-6:-1]
related_SA_Hate_doc_38 = cosine_similarities_SA_HAte_38.argsort()[:-6:-1]
related_SA_Hate_doc_39 = cosine_similarities_SA_HAte_39.argsort()[:-6:-1]
related_SA_Hate_doc_40 = cosine_similarities_SA_HAte_40.argsort()[:-6:-1]
related_SA_Hate_doc_41 = cosine_similarities_SA_HAte_41.argsort()[:-6:-1]
related_SA_Hate_doc_42= cosine_similarities_SA_HAte_42.argsort()[:-6:-1]
related_SA_Hate_doc_43= cosine_similarities_SA_HAte_43.argsort()[:-6:-1]

In [96]:
related_SA_Hate_doc_1

array([ 920, 1130, 1137,  956, 1017], dtype=int64)

In [97]:
related_SA_Hate_doc_2

array([ 743, 1027, 1211,  925,  409], dtype=int64)

In [98]:
related_SA_Hate_doc_3

array([1140,  315, 1130,   16,  597], dtype=int64)

In [99]:
related_SA_Hate_doc_4

array([157, 415, 588, 127,  99], dtype=int64)

In [100]:
related_SA_Hate_doc_5

array([1180,  357,  783,  564,  700], dtype=int64)

In [101]:
related_SA_Hate_doc_6

array([597, 487, 848, 539, 500], dtype=int64)

In [102]:
related_SA_Hate_doc_7

array([1074,   28, 1077,  753,   45], dtype=int64)

In [103]:
related_SA_Hate_doc_8

array([816, 733, 731, 334, 991], dtype=int64)

In [104]:
related_SA_Hate_doc_9

array([601, 933, 599, 600, 434], dtype=int64)

In [105]:
related_SA_Hate_doc_10

array([  55,  226,  175,  102, 1129], dtype=int64)

In [106]:
related_SA_Hate_doc_11

array([124, 616, 233, 951, 103], dtype=int64)

In [107]:
related_SA_Hate_doc_12

array([1077,  247, 1072, 1038,  551], dtype=int64)

In [108]:
related_SA_Hate_doc_13

array([ 836,  855, 1025,  891,  201], dtype=int64)

In [109]:
related_SA_Hate_doc_14

array([1123,  258, 1141,  908,  586], dtype=int64)

In [110]:
related_SA_Hate_doc_15

array([  55,  304, 1203,   17,  391], dtype=int64)

In [111]:
related_SA_Hate_doc_16

array([ 539,  905,  717, 1079,  102], dtype=int64)

In [112]:
related_SA_Hate_doc_17

array([ 31, 702, 114, 462, 902], dtype=int64)

In [113]:
related_SA_Hate_doc_18

array([1072,  985,   55, 1074,  175], dtype=int64)

In [114]:
related_SA_Hate_doc_19

array([ 983, 1139,  423, 1096, 1030], dtype=int64)

In [115]:
related_SA_Hate_doc_20

array([ 754,  776, 1021,  714,  443], dtype=int64)

In [116]:
related_SA_Hate_doc_21

array([1072,   71, 1048,  906,  813], dtype=int64)

In [117]:
related_SA_Hate_doc_22

array([1057, 1123,  403,  851,  887], dtype=int64)

In [118]:
related_SA_Hate_doc_23

array([702, 281, 330, 707, 743], dtype=int64)

In [119]:
related_SA_Hate_doc_24

array([ 331,  710,  272, 1152, 1022], dtype=int64)

In [120]:
related_SA_Hate_doc_25

array([ 710,   55,  741, 1129, 1011], dtype=int64)

In [121]:
related_SA_Hate_doc_26

array([780, 634,   3, 870, 343], dtype=int64)

In [122]:
related_SA_Hate_doc_27

array([152, 403, 802, 851, 559], dtype=int64)

In [123]:
related_SA_Hate_doc_28

array([ 305, 1045,  822,  169,  601], dtype=int64)

In [124]:
related_SA_Hate_doc_29

array([  58, 1156,   26,  156,  795], dtype=int64)

In [125]:
related_SA_Hate_doc_30

array([405, 322, 833, 708, 657], dtype=int64)

In [126]:
related_SA_Hate_doc_31

array([1021,  636,  620,  823,  252], dtype=int64)

In [127]:
related_SA_Hate_doc_32

array([ 549, 1140,  315,   16,  837], dtype=int64)

In [128]:
related_SA_Hate_doc_33

array([ 462,  873,  179, 1072, 1022], dtype=int64)

In [129]:
related_SA_Hate_doc_34

array([ 11, 675, 979, 627, 304], dtype=int64)

In [130]:
related_SA_Hate_doc_35

array([ 524, 1073, 1022,  689,  349], dtype=int64)

In [131]:
related_SA_Hate_doc_36

array([173, 343, 809, 531, 720], dtype=int64)

In [132]:
related_SA_Hate_doc_37

array([ 408, 1200,  837,  622,  210], dtype=int64)

In [133]:
related_SA_Hate_doc_38

array([  62, 1081,  504,   17, 1192], dtype=int64)

In [134]:
related_SA_Hate_doc_39

array([ 679,  565, 1123,   22, 1033], dtype=int64)

In [135]:
related_SA_Hate_doc_40

array([ 669, 1136,  590,  141,  296], dtype=int64)

In [136]:
related_SA_Hate_doc_41

array([ 748, 1200,  602,  796, 1066], dtype=int64)

In [137]:
related_SA_Hate_doc_42

array([ 818,  602, 1090,   59,    3], dtype=int64)

In [138]:
related_SA_Hate_doc_43

array([1021, 1010, 1000,  948,  854], dtype=int64)